spring:
  application:
    name: provider-server-1

eureka:
  client:
    register-with-eureka: true # 默认是打开的
    fetch-registry: true # 默认是打开的
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    registry-fetch-interval-seconds: 2 # 每两秒就从注册中拉一次地址信息
provider:
  name: "provider-2"


# 用于支持spring actuator的配置热更新
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
