server:
  port: 9527

spring:
  application:
    name: zuul-server

eureka:
  client:
    register-with-eureka: true # 默认是打开的
    fetch-registry: true # 默认是打开的
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    registry-fetch-interval-seconds: 2 # 每两秒就从注册中拉一次地址信息
zuul:
  ignored-services: "*"
  routes:
    consumer:
      serviceId: consumer-server-1
      path: /consumer/**


ribbon:
  ConnectTimeot: 60000 # 连接超时时间（ms）
  ReadTimeot: 60000 # 通信超时时间（ms）
  # OkToRertryOnAllOperations: ture # 是否对所有操作重试
  # MaxAutoRetriesNextServer: 1 #同一个服务不同实例的重试次数
  # MaxAutoRetries: 1 #同一实例的重试次数
  
# hystrix:
#   command:
#     default:
#       execution:
#         isolation:
#           thread:
#             timeoutInMillisecond: 10000 #熔断超时时长 10000ms
